---

- name: Apply basic ssh config on all hosts
  hosts: all
  tags: 
   - auth
   - ssh
  roles:
    - ssh_authorized_keys
    - sshd
  vars: 
    - ansible_ssh_user: 'ansible'

- name: Apply common basic config on all hosts
  hosts: all
  tags: 
   - auth
   - base
  roles:
    - home_environment
    - base-packages

- name: Install info-beamer binary
  hosts: all
  tags: 
   - binary
   - bin
   - info-beamer
   - info
   - beamer
   - setup
   - info_beamer
  roles:
    - info-beamer

- name: Install special services for info-beamer - ffbsee
  hosts: all
  tags:
   - special
   - ffbsee
   - sevices
   - ffbsee_special
   - ffbsee-special
   - crazy
   - break
   - pause
   - pausenmusik
   - musik
   - ccc
  roles:
   - ffbsee_special
   - pausenmusik
